apiVersion: sa.upbound.io/v1alpha1
kind: XBackstage
metadata:
  name: solution-idp
spec:
  parameters:
    id: "solution-idp-non-prod-frontend"
    region: "us-west-2"
    providerConfigName: "default"
    ingress:
      enabled: true
      host: "backstage-solution-idp.upboundrocks.cloud"
      clusterIssuer: "letsencrypt-prod"
      className: "nginx"
    replicas: 3
    image:
      registry: xpkg.upbound.io
      repository: upbound/backstage
      tag: v0.6.0
    config:
      app:
        title: "solution-idp"
      organization:
        name: "upbound"
      integrations:
        github:
          - host: github.com
            token: '${GITHUB_TOKEN}'
      kubernetes:
        frontend:
          podDelete:
            enabled: true
        skipMetricsLookup: true
        serviceLocatorMethod:
          type: "multiTenant"
        auth:
          providers:
            upbound: {}
        clusterLocatorMethods:
          - type: "config"
            clusters:
              - url: "https://proxy.upbound-34.168.72.36.nip.io/apis/spaces.upbound.io/v1beta1/namespaces/solution-idp-non-prod-frontend/controlplanes/frontend/k8s"
                name: "solution-idp-non-prod-frontend-frontend"
                authProvider: "upbound"
                skipMetricsLookup: true
                skipTLSVerify: true
                authMetadata:
                  'upbound.io/organization': "upbound"
                  'upbound.io/token': '${UP_ROBOT_TOKEN}'
                gitFilePathPattern: "state/solution-idp-non-prod/frontend/30-claims/$$Kind-$$Namespace-$$Name"
        objectTypes:
          - configmaps
          - deployments
          - pods
          - services
      kubernetesIngestor:
        mappings:
          systemModel: "cluster-namespace"
        components:
          customWorkloadTypes:
            - group: "aws.platform.upbound.io"
              apiVersion: "v1alpha1"
              plural: "xeks"
              singular: "xeks"
            - group: "aws.platform.upbound.io"
              apiVersion: "v1alpha1"
              singular: "xnetwork"
              plural: "xnetworks"
            - group: "aws.platform.upbound.io"
              apiVersion: "v1alpha1"
              plural: "xpodidentities"
              singular: "xpodidentity"
            - group: "platform.upbound.io"
              apiVersion: "v1alpha1"
              plural: "xsqlinstances"
              singular: "XSQLInstance"
            - group: "aws.platform.upbound.io"
              apiVersion: "v1alpha1"
              singular: "XSQLInstance"
              plural: "xsqlinstances"
            - group: "azure.platform.upbound.io"
              apiVersion: "v1alpha1"
              singular: "XSQLInstance"
              plural: "xsqlinstances"
            - group: "azure.platform.upbound.io"
              apiVersion: "v1alpha1"
              singular: "XNetwork"
              plural: "xnetworks"
        crossplane:
          xrds:
            publishPhase:
              allowRepoSelection: false
              allowedTargets:
                - github.com
              target: github
              git:
                repoUrl: github.com?owner=upbound&repo=solution-idp
                targetBranch: main
    secretSync:
      - destRef:
          name: up-secret
          namespace: backstage
        sourceRef:
          name: solution-idp-non-prod-frontend-robot-token
          namespace: crossplane-system
    infrastructure:
      ingressNginx:
        enabled: true
      certManager:
        enabled: true
      lbController:
        enabled: true
      externalDNS:
        enabled: true
        # upboundrocks.cloud
        route53ZoneId: "Z0115025YFQ7ZQF6BJ6N"
      eks:
        enabled: true
        accessConfig:
          bootstrapClusterCreatorAdminPermissions: true
          authenticationMode: API
        iam:
          principalArn: arn:aws:iam::609897127049:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_AdministratorAccess_d703c73ed340fde7
        version: "1.29"
        nodes:
          count: 1
          instanceType: "m4.2xlarge"
