apiVersion: platform.shell.com/v1alpha1
kind: StorageBucket
metadata:
  annotations:
    upbound.backstage.io/source-info: >-
      {"pushToGit":true,"gitBranch":"siva-demo","gitRepo":"github.com?owner=upbound&repo=solution-idp","gitLayout":"cluster-scoped","basePath":"integrated-gas-control-plane/default/StorageBucket"}
    upbound.backstage.io/add-to-catalog: 'true'
    upbound.backstage.io/owner: group:default/platform-engineer
    upbound.backstage.io/system: default
    upbound.backstage.io/source-file-url: >-
      https://github.com/upbound/solution-idp/blob/siva-demo/state/solution-idp-non-prod/frontend/30-claims/integrated-gas/production/StorageBucket-default-usage-and-charges-bucket.yaml
  name: usage-and-charges-bucket
  namespace: default
spec:
  parameters:
    versioning: true
    acl: private
    provider: aws
    region: us-west
  compositeDeletePolicy: Background
  writeConnectionSecretToRef:
    name: up-secret
  compositionUpdatePolicy: Automatic
