apiVersion: platform.nord.com/v1alpha1
kind: StorageBucket
metadata:
  annotations:
    upbound.backstage.io/source-info: >-
      {"pushToGit":true,"gitBranch":"siva-demo","gitRepo":"github.com?owner=upbound&repo=solution-idp","gitLayout":"cluster-scoped","basePath":"nord/default/StorageBucket"}
    upbound.backstage.io/add-to-catalog: 'true'
    upbound.backstage.io/owner: group:default/platform-engineer
    upbound.backstage.io/system: default
    upbound.backstage.io/source-file-url: >-
      https://github.com/upbound/solution-idp/blob/siva-demo/state/solution-idp-non-prod/frontend/30-claims/nord/production/StorageBucket-default-customer-address-storage.yaml
  name: customer-address-storage
  namespace: default
spec:
  parameters:
    versioning: true
    acl: private
    provider: azure
    region: europe-west
  compositeDeletePolicy: Background
  writeConnectionSecretToRef:
    name: up-secret
  compositionUpdatePolicy: Automatic
