apiVersion: platform.upbound.io/v1alpha1
kind: SQLInstance
metadata:
  annotations:
    upbound.backstage.io/source-info: >-
      {"pushToGit":true,"gitBranch":"javid-labs","gitRepo":"github.com?owner=upbound&repo=solution-idp","gitLayout":"cluster-scoped","basePath":"solution-idp-non-prod-frontend-frontend/default/SQLInstance"}
    upbound.backstage.io/add-to-catalog: 'true'
    upbound.backstage.io/owner: group:default/javid
    upbound.backstage.io/system: default
    upbound.backstage.io/source-file-url: >-
      https://github.com/upbound/solution-idp/blob/javid-labs/solution-idp-non-prod-frontend-frontend/default/SQLInstance/azure-test.yaml
  name: azure-test
  namespace: default
spec:
  parameters:
    cloud: Azure
    deletionPolicy: Delete
    engine: postgres
    engineVersion: '11'
    providerConfigName: default
    region: westus2
    storageGB: 32
  compositeDeletePolicy: Background
