apiVersion: platform.shell.com/v1alpha1
kind: Network
metadata:
  annotations:
    upbound.backstage.io/source-info: >-
      {"pushToGit":true,"gitBranch":"siva-demo","gitRepo":"github.com?owner=upbound&repo=solution-idp","gitLayout":"cluster-scoped","basePath":"integrated-gas-control-plane/default/Network"}
    upbound.backstage.io/add-to-catalog: 'true'
    upbound.backstage.io/owner: group:default/platform-engineer
    upbound.backstage.io/system: default
    upbound.backstage.io/source-file-url: >-
      https://github.com/upbound/solution-idp/blob/siva-demo/domains/integrated-gas/production/Network-default-secured-network-aws.yaml
  name: demo-network-aws
  namespace: default
spec:
  parameters:
    cidrBlock: 10.0.0.0/16
    provider: aws
    region: europe-west
    tags:
      CostCenter: cc-86535
      ProjectName: DemoProject
  crossplane:
    compositionUpdatePolicy: Automatic
