apiVersion: dbaas.shell.com/v1alpha1
kind: SQLInstance
metadata:
  annotations:
    upbound.backstage.io/source-info: >-
      {"pushToGit":true,"gitBranch":"siva-demo","gitRepo":"github.com?owner=upbound&repo=solution-idp","gitLayout":"cluster-scoped","basePath":"renewables-control-plane/default/SQLInstance"}
    upbound.backstage.io/add-to-catalog: 'true'
    upbound.backstage.io/owner: group:default/platform-engineer
    upbound.backstage.io/system: default
    upbound.backstage.io/source-file-url: >-
      https://github.com/upbound/solution-idp/blob/siva-demo/state/solution-idp-non-prod/frontend/30-claims/renewables/production/SQLInstance-default-postgres-db-azure.yaml
  name: postgres-db-azure
  namespace: default
spec:
  parameters:
    engine: postgres
    provider: aws
    purpose: development
    region: europe-west
  compositeDeletePolicy: Background
  writeConnectionSecretToRef:
    name: postgres-db-aws-connection
  compositionUpdatePolicy: Automatic
