apiVersion: platform.upbound.io/v1alpha1
kind: SQLInstance
metadata:
  annotations:
    upbound.backstage.io/source-info: >-
      {"pushToGit":true,"gitBranch":"siva-labs","gitRepo":"github.com?owner=upbound&repo=solution-idp","gitLayout":"cluster-scoped","basePath":"solution-idp-non-prod-frontend/default/SQLInstance"}
    upbound.backstage.io/add-to-catalog: 'true'
    upbound.backstage.io/owner: group:default/platform-team
    upbound.backstage.io/system: default
    upbound.backstage.io/source-file-url: >-
      https://github.com/upbound/solution-idp/blob/siva-labs/state/solution-idp-non-prod/frontend/30-claims/SQLInstance-default-postgres-db.yaml
  name: postgres-db
  namespace: default
spec:
  parameters:
    cloud: AWS
    deletionPolicy: Delete
    engine: postgres
    engineVersion: '15'
    passwordSecretRef:
      key: password
      name: postgres-db-secret
      namespace: default
    providerConfigName: default
    region: eu-west-1
    storageGB: 15
  compositeDeletePolicy: Background
  writeConnectionSecretToRef:
    name: up-secret
  compositionUpdatePolicy: Automatic
