apiVersion: example.org/v1alpha1
kind: VirtualMachine
metadata:
  annotations:
    upbound.backstage.io/source-info: >-
      {"pushToGit":true,"gitBranch":"main","gitRepo":"github.com?owner=upbound&repo=solution-idp","basePath":"solution-idp-non-prod-frontend-frontend/default/VirtualMachine"}
    upbound.backstage.io/add-to-catalog: 'true'
    upbound.backstage.io/owner: group:default/jay
    upbound.backstage.io/system: default
    upbound.backstage.io/source-file-url: >-
      https://github.com/upbound/solution-idp/blob/main/state/solution-idp-non-prod/frontend/30-claims/VirtualMachine-default-test.yaml
  name: test
  namespace: default
spec:
  parameters:
    ami: amazon
    instanceType: tiny
    region: us-east-2
  compositeDeletePolicy: Background
