apiVersion: platform.multiverse.com/v1alpha1
kind: WebApp
metadata:
  annotations:
    upbound.backstage.io/source-info: >-
      {"pushToGit":true,"gitBranch":"siva-demo","gitRepo":"github.com?owner=upbound&repo=solution-idp","gitLayout":"cluster-scoped","basePath":"multiverse-control-plane/default/WebApp"}
    upbound.backstage.io/add-to-catalog: 'true'
    upbound.backstage.io/owner: group:default/platform-engineer
    upbound.backstage.io/system: default
    upbound.backstage.io/source-file-url: >-
      https://github.com/upbound/solution-idp/blob/siva-demo/state/solution-idp-non-prod/frontend/30-claims/multiverse/production/WebApp-default-order-service.yaml
  name: order-service
  namespace: default
spec:
  parameters:
    image: nginx
    ingress:
      enabled: true
    port: 8080
    replicas: 1
    service:
      enabled: true
    serviceAccount: default
  crossplane:
    compositionUpdatePolicy: Automatic
