name: Deploy to k8s

on:
  push:
    branches:
      - siva-demo

env:
  UP_API_TOKEN: ${{ secrets.UP_API_TOKEN }}
  UP_ORG: ${{ secrets.UP_ORG }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Install and login with up
        if: env.UP_API_TOKEN != '' && env.UP_ORG != ''
        uses: upbound/action-up@v1
        with:
          api-token: ${{ secrets.UP_API_TOKEN }}
          organization: ${{ secrets.UP_ORG }}

      - name: Set Upbound context
        run: up ctx upbound-demo/upbound-gcp-eu-west-3/integrated-gas/production

      # - name: Configure kubeconfig
      #   run: |
      #     mkdir -p $HOME/.kube
      #     echo "${{ secrets.KUBECONFIG_CONTENT }}" > $HOME/.kube/config

      - name: Apply manifests
        run: |
          kubectl apply -f state/solution-idp-non-prod/frontend/30-claims/